### ISSUE TITLE
[lean-lang.org] wrong link

### ISSUE THREAD

**Issue by fpvandoorn** [leanprover/leanprover.github.io#113]
https://lean-lang.org/people/
contains a link to
https://lean-fro.org/people/
which should be
https://lean-fro.org/team/

[I don't think the repo for `lean-lang.org` is public, so I cannot submit a PR]

**Comment by fpvandoorn** [comment]
More minor: ideally https://www.contrib.andrew.cmu.edu/~fpv/ (link on the same page) can be updated to https://florisvandoorn.com/

**Comment by Kha** [comment]
Done, thanks!
