### ISSUE TITLE
cursor position is off on "Try Lean" page

### ISSUE THREAD

**Issue by leodemoura** [leanprover/leanprover.github.io#29]
On Windows 7 (I will try Windows 8 later), the cursor position is completely off on the "Try Lean" page.

See the position of the cursor in the following snapshot:

![image](https://cloud.githubusercontent.com/assets/2778936/6577356/93606fb8-c6fa-11e4-9e0e-fca7ace9594a.png)

Now suppose we type "12345". Here is the result

![image](https://cloud.githubusercontent.com/assets/2778936/6577373/c2159c66-c6fa-11e4-9840-693850443402.png)

The problem happens when I use Chrome or Firefox.
The weird thing is that the tutorial page is fine. The ACE editor seems to use a different font in the tutorial page. See the following snapshop:

![image](https://cloud.githubusercontent.com/assets/2778936/6577395/fb92a060-c6fa-11e4-85ee-22d952b40a4c.png)

The problem does not happen on Linux + Chrome.

**Comment by soonhokong** [comment]
@leodemoura, thanks for the report. I'm looking at this issue now.

**Comment by soonhokong** [comment]
I figure out the reason. There is a `.css` file only loaded with tutorial. I'll fix it soon.

**Comment by leodemoura** [comment]
Thanks!
