### ISSUE TITLE
Issues with some symbolic shortcuts

### ISSUE THREAD

**Issue by rkirsling** [leanprover/leanprover.github.io#30]
Some of the backslash shortcuts aren't producing their expected output in the online editor.

According to the table in Chapter 3.3 of the tutorial:
* `\iff` and `\lr` should produce ↔
* `\not` and `\neg` should produce ¬

In the first case, `\lr` works as expected (as does `\<->` and `\leftrightarrow`), but `\iff` produces ⇔ instead, which results in an `unexpected token` error. The cause here seems to be [input-method.js#L689](https://github.com/leanprover/leanprover.github.io/blob/master/js/input-method.js#L689).

The second case is weirder: `\neg` works correctly (as does `\lnot`), but `\not` produces [U+0338](https://codepoints.net/U+0338), a sort of "combining slash" character. Looking at [input-method.js#L701](https://github.com/leanprover/leanprover.github.io/blob/master/js/input-method.js#L701) though, nothing really seems amiss. :confused:

**Comment by soonhokong** [comment]
@rkirsling, I moved this to https://github.com/leanprover/tutorial/issues/81
