### ISSUE TITLE
font sizes uneven

### ISSUE THREAD

**Issue by avigad** [leanprover/leanprover.github.io#31]
On the "Documentation" page, the last two lines are in a slightly larger font on my browser. On the "People" page, the items are slightly smaller than the list headers.

**Comment by soonhokong** [comment]
It follows from a strange behavior of [kramdown][kramdown], the markdown converter that we're using. For some cases, it wraps a list item (`<li>` tag) with a `<p>` tag, while sometimes it doesn't. 9b90567dcb391e6e6a4e77243e9779641e8e3862 fixes this problem, at least for documentation page.

[kramdown]: http://kramdown.gettalong.org/
