### ISSUE TITLE
proposals

### ISSUE THREAD

**Issue by avigad** [leanprover/leanprover.github.io#33]
I reviewed the Lean web pages, and I would like to suggest come changes.

(1) The "about" button should come first. When people come to a strange new page, it is reasonable to want to know what is there.

(2) On the "about" page it would be helpful to tell people about the collaborative nature of Lean. I would suggest adding a second paragraph:

"The Lean project was launched by Leonardo de Moura at Microsoft Research in 2013. It is a collaborative open source project, hosted on [github]. Contributions to the code base and library are welcome."

(3) "Publications" can be merged with "Documentation", at the bottom.
 
Later, we can add information about mailing lists and stackoverflow.

(4) Under Documentation, it would be helpful to let people know what to expect when they click the tutorial buttons. I would make a separate section "Tutorial", with the following entries:

* There is an [online tutorial], which is presented alongside a version of Lean running in your browser.
* You can also read the [pdf version].

(5) It is disconcerting that users just clicking around get taken to a totally different page with a slow load process when they click "Try Lean". It would be friendlier if the button took them to a page that says something like this:

You can experiment with an [online version of Lean] that runs in your browser.

Actually, I don't know if we need a separate button for this. Instead, we could delete the "Try Lean" and add this line to "About":

You can experiment with an [online version of Lean] that runs in your browser, or use an [online tutorial].

We can all add this same line to the bottom of the Download page.

Thoughts? I would be happy to implement these changes.

**Comment by avigad** [comment]
Also on the Documentation page, we should add a line indicating that users can browse the libraries on the github repositories, either directly or using the markdown files. Maybe we should add a section "Libraries" with that information. We should also indicate that there are both a standard library and a HoTT library.

**Comment by leodemoura** [comment]
All modifications sound good to me.
BTW, to change the navigation bar, you have to edit the following file
	https://github.com/leanprover/leanprover.github.io/blob/master/_data/navigation.yml

Thanks,
Leo

**Comment by soonhokong** [comment]
@leodemoura and @avigad, I just updated the webpage by adding what @avigad suggested (see 162db4d24afe750dad1b6cd075cfa36c7bdc803d). You may need to press <kbd>F5</kbd> to refresh the pages to see the new one.

Somehow, we have two different font sizes (18pt and 20pt) being used in about and documentation pages. I'm working on that issue.

If you have other suggestions, please feel free to add them here.

**Comment by soonhokong** [comment]
> Somehow, we have two different font sizes (18pt and 20pt) being used in about and documentation pages. I'm working on that issue.

Now, it looks good on my machines. Please let me know if it's not the case on your machines.

**Comment by avigad** [comment]
Thanks! I really it like it now -- it is cleaner, simpler, and more intuitive. I will also add a section on the documentation page describing the libraries, and issue a pull request, so you can see if you like it.
