### ISSUE TITLE
Replacement of symbols not working in tutorial

### ISSUE THREAD

**Issue by wrsaunde** [leanprover/leanprover.github.io#48]
Tutorial claims that you can type \to or \nat and have them replaced by the appropriate symbol, but this functionality doesn't seem to be working (in Chrome on ubuntu)

**Comment by wrsaunde** [comment]
Seem to get "Uncaught ReferenceError: corrections is not defined" in developer console
in js/main_live.js
at 193

**Comment by soonhokong** [comment]
@wrsaunde, thanks for the report. I'll check things up.

**Comment by soonhokong** [comment]
Fixed.

It was a side-effect of the latest build failure in leanprover/tutorial repo: https://travis-ci.org/leanprover/tutorial/builds/119869686

There was a test failure and `js/completion.js` file was not generated correctly as a consequence. I fixed the problem manually for now. I'll update the tutorial soon.
